extends Node

signal day_advanced(day:int, month:int, year:int)
signal time_speed_changed(speed:int)
signal cash_changed(new_cash:float, delta:float, reason:String)
signal contract_accepted(contract_id:String)
signal contract_completed(contract_id:String)
signal vessel_chartered(vessel_id:String)
signal vessel_purchased(vessel_id:String)
signal vessel_departed(vessel_id:String, origin_port_id:String, destination_port_id:String)
signal vessel_arrived(vessel_id:String, port_id:String)
signal captain_hired(person_id:String, vessel_id:String)
signal crew_hired(vessel_id:String, amount:int)
signal provisions_loaded(vessel_id:String, days:int)
signal cargo_loading_started(vessel_id:String, contract_id:String)
signal cargo_loading_progress(vessel_id:String, progress:float)
signal cargo_loading_completed(vessel_id:String)
signal ship_welfare_changed(vessel_id:String, morale:float, health:float)
signal cargo_condition_changed(vessel_id:String, condition:float)
signal cargo_claim_paid(vessel_id:String, amount:float, cargo_condition:float)
signal voyage_started(voyage_id:String)
signal voyage_progress(voyage_id:String, progress:float)
signal voyage_event_requested(voyage_id:String, event_id:String)
signal voyage_event_resolved(voyage_id:String, event_id:String, choice:String)
signal facility_lease_started(facility_id:String)
signal vessel_repaired(vessel_id:String)
signal facility_construction_started(facility_id:String)
signal facility_construction_progress(facility_id:String, progress:float)
signal facility_construction_completed(facility_id:String)
signal shipyard_job_started(job_id:String)
signal shipyard_job_completed(job_id:String)
signal research_completed(technology_id:String)
signal world_event_started(event_id:String)
signal selection_changed(entity_type:String, entity_id:String)
